CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Bookmarks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "UserEmail" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookmarks" PRIMARY KEY ("Id")
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserEmail" text NOT NULL,
    "Address" text,
    "Country" text,
    "City" text,
    "PhoneNumber" text,
    "OrderDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "DeliveryMethod" text,
    "PaymentMethod" text,
    "TotalAmount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric(18,2) NOT NULL,
    "Stock" integer NOT NULL,
    "Gender" text,
    "ImageUrl" text,
    "ImageUrls" text,
    "Tags" text,
    "Colors" text,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE "ShoppingCarts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserEmail" text NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Size" text,
    "Color" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Address" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductName" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "ImageUrl" text,
    "Size" text,
    "Color" text,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SupportRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer,
    "RequestType" text NOT NULL,
    "CustomerName" text NOT NULL,
    "CustomerEmail" text NOT NULL,
    "Message" text NOT NULL,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "AdminResponse" text,
    CONSTRAINT "PK_SupportRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupportRequests_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id")
);

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE INDEX "IX_SupportRequests_OrderId" ON "SupportRequests" ("OrderId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623043454_InitialCreate', '8.0.21');

COMMIT;

